using System;
using UnityEngine;
using Utils;

public class Projectile : MonoBehaviour
{
    #region Configuration
    [Tooltip("The force generated by the projectile when thrown.")]
    [SerializeField] float throwPower = 20f;
    [Tooltip("The force generated by the projectile in flight, this is generated continuously in direction of travel.")]
    [SerializeField] float flightPower = 10f;
    [Tooltip("The upward lift force generated by the projectile in flight, this is generated continuously upwards.\n" +
        "This value is a percentage of mass, 1 will always fly forwards.\n" +
        "< 1 Will fall." +
        "> 1 will rise.")]
    [Range(0f, 2f)]
    [SerializeField] float flightLift = 1f;
    [SerializeField] float damage = 10f;
    [SerializeField] float lifeTime = 10f; // Time in seconds before the projectile is destroyed
    #endregion

    #region Cached Components
    Rigidbody rb;
    #endregion

    #region Runtime Variables
    // Store direction of force in 2D since height will not be considerded, height dertermined by spawn location and then physics
    Vector2 direction;
    float destroyTime = 0f;
    GameObject firingParent;
    #endregion

    #region Properties
    public Vector2 Direction
    {   
        get { return direction; }
        set { direction = value.normalized; } // Ensure direction is always normalized when set
    }
    public GameObject FiringParent
    {
        get { return firingParent; }
        set { firingParent = value; }
    }
    private Vector3 Direction3D
    {
        // We do not normnalize this since the direction is already normalized and we want to keep the flight component as is.
        get 
        {
            float x = direction.x * flightPower;
            float y = (rb?.mass ?? 1) * -Physics.gravity.y * flightLift; // Upward lift is based on mass to keep it consistent
            float z = direction.y * flightPower;
            return new Vector3(x, y, z); 
        }
    }

    #endregion

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        if (direction == Vector2.zero)
        {
            Debugger.LogWarning("Direction not set for projectile. Defaulting to forward.");
            direction = new Vector2(transform.forward.x, transform.forward.z).normalized; // Default direction if not set
        }

        FindReferences();

        rb.AddForce(new Vector3(direction.x, 0, direction.y) * throwPower, ForceMode.Impulse);
        destroyTime = Time.time + lifeTime;
    }

    private void FindReferences()
    {
        rb = GetComponent<Rigidbody>();
        if (!rb) Debugger.LogError("Rigidbody component missing from projectile.");
    }

    private void Update()
    {
        if (Time.time >= destroyTime)
        {
            Destroy(gameObject);
        }
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        Flight();
    }

    private void Flight()
    {
        if (!rb) return;

        rb.AddForce(Direction3D, ForceMode.Force);
    }
    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject == firingParent) return; // Ignore collision with the firing parent
        // Check if firing parent has a child with the same game object as the other
        if (firingParent && other.transform.IsChildOf(firingParent.transform)) return; // Ignore collision with children of the firing parent

        Destroy(gameObject);

        if (!other.TryGetComponent<Health>(out var health)) return;
        if (!health.GetComponent<Enemy>()) return;

        health.TakeDamage(damage);
        

    }
}
